### PR TITLE
Functions now return error codes

### PR DESCRIPTION
**Pull request by EfeYks534**
Functions such as `MiniGFX_CreateWindow`, `MiniGFX_LoadSprite` or `MiniGFX_LoadFont` now return error codes instead of blindly exitting the program when an error happens. All sprite functions now take sprite pointers instead of sprite objects for better performance.

### CODE REVIEW

**Comment by laurenloco** [comment]
Hey. Although it is good that functions return error codes, the purpose of minigfx is to be simple for the user. I think this would be suitable for the header file.

**Comment by laurenloco** [comment]
> Hey. Although it is good that functions return error codes, the purpose of minigfx is to be simple for the user. I think this would be suitable for the header file.

P. S.
I can try to implement these changes on my own

**Comment by EfeYks534** [comment]
I understand what you mean and I did try to keep the simplicity there, but there are so many cases where the program will outright crash because of unchecked errors

**Comment by laurenloco** [comment]
> I understand what you mean and I did try to keep the simplicity there, but there are so many cases where the program will outright crash because of unchecked errors

Check if the changes I did on the functions you changed are right, and if not, please contribute.

**Pull request closed without merging**
